package com.quip.backend.problem.mapper.dto;

import com.quip.backend.problem.dto.ProblemDto;
import com.quip.backend.problem.dto.ProblemCreateDto;
import com.quip.backend.problem.model.Problem;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface ProblemDtoMapper {

    /**
     * Maps the domain model Problem to ProblemDto for GET requests.
     */
    @Mapping(target = "correctAnswerIndex", ignore = true)
    @Mapping(target = "created_at", ignore = true)
    @Mapping(target = "updated_at", ignore = true)
    ProblemDto toProblemDto(Problem problem);

    /**
     * Maps ProblemCreateDto to Problem for POST requests.
     */
    @Mapping(target = "problemId", ignore = true)  // Exclude as it's generated by the system
    @Mapping(target = "mediaUrl", ignore = true)   // System-generated media URL
    Problem toProblem(ProblemCreateDto problemCreateDto);
}
