package com.quip.backend.problem.mapper.dto.request;

import com.quip.backend.problem.dto.request.CreateProblemRequestDto;
import com.quip.backend.problem.model.Problem;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

/**
 * MapStruct mapper interface for converting CreateProblemRequestDto to Problem entity.
 * <p>
 * This interface defines mapping rules for transforming request DTOs into domain entities.
 * It uses MapStruct to automatically generate the implementation at compile time.
 * </p>
 */
@Mapper(componentModel = "spring")
public interface CreateProblemRequestDtoMapper {


    /**
     * Converts a CreateProblemRequestDto to a Problem entity.
     * <p>
     * This mapping:
     * - Maps memberId to contributorId
     * - Ignores id (will be generated by the database)
     * - Ignores mediaFileId (handled separately)
     * - Ignores isValid (set by business logic)
     * - Ignores serverId (set by business logic)
     * - Ignores audit fields (createdAt, updatedAt, createdBy, updatedBy)
     * </p>
     *
     * @param dto The DTO to convert
     * @return A Problem entity with mapped values
     */
    @Mappings({
            @Mapping(target = "id", ignore = true),
            @Mapping(target = "contributorId", source = "memberId"),
            @Mapping(target = "mediaFileId", ignore = true),
            @Mapping(target = "isValid", ignore = true),
            @Mapping(target = "serverId", ignore = true),
            @Mapping(target = "createdAt", ignore = true),
            @Mapping(target = "updatedAt", ignore = true),
            @Mapping(target = "createdBy", ignore = true),
            @Mapping(target = "updatedBy", ignore = true)
    })
    Problem toProblem(CreateProblemRequestDto dto);
}