package com.quip.backend.problem.mapper.dto.request;

import com.quip.backend.problem.dto.request.CreateProblemCategoryRequestDto;
import com.quip.backend.problem.model.ProblemCategory;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

/**
 * MapStruct mapper interface for converting CreateProblemCategoryRequestDto to ProblemCategory entity.
 * <p>
 * This interface defines mapping rules for transforming problem category request DTOs into domain entities.
 * It uses MapStruct to automatically generate the implementation at compile time.
 * </p>
 */
@Mapper(componentModel = "spring")
public interface CreateProblemCategoryRequestDtoMapper {
    /**
     * Converts a CreateProblemCategoryRequestDto to a ProblemCategory entity.
     * <p>
     * This mapping:
     * - Maps problemCategoryName to categoryName
     * - Maps problemCategoryDescription to description
     * - Ignores id (will be generated by the database)
     * - Ignores serverId (set explicitly in the service layer)
     * - Ignores audit fields (createdAt, updatedAt, createdBy, updatedBy)
     * </p>
     *
     * @param createProblemCategoryRequestDto The DTO to convert
     * @return A ProblemCategory entity with mapped values
     */
    @Mappings({
            @Mapping(target = "id", ignore = true),
            @Mapping(target = "serverId", ignore = true),
            @Mapping(target = "categoryName", source = "problemCategoryName"),
            @Mapping(target = "description", source = "problemCategoryDescription"),
            @Mapping(target = "createdAt", ignore = true),
            @Mapping(target = "updatedAt", ignore = true),
            @Mapping(target = "createdBy", ignore = true),
            @Mapping(target = "updatedBy", ignore = true)
    })
    ProblemCategory toProblemCategory(CreateProblemCategoryRequestDto createProblemCategoryRequestDto);
}
