spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

logging:
  file:
    name: logs/backend.log
  level:
    com.quip.backend: INFO
    org.springframework: WARN
    org.mybatis: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

mybatis:
  mapper-locations: classpath*:/com/quip/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    type-handlers:
      - com.quip.backend.config.handler.StringArrayTypeHandler

app:
  assets:
    base-url: http://localhost:8080/assets/
    base-path: src/main/resources/static/