# Production Environment Configuration for Agent
# This configuration extends the base config.yaml for production deployments

# Agent Configuration
app:
  name: "agent"
  version: "1.0.0"
  description: "Agent Service for Quip Bot - Production"

# Backend API Configuration
backend:
  url: ${BACKEND_URL:http://quip-backend-app:8080}

# Logging Configuration - Production optimized
logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:"%(asctime)s - %(name)s - %(levelname)s - %(message)s"}
  handlers:
    - console
    - file
  file_path: ${LOG_FILE_PATH:logs/agent.log}
  # Production log levels - less verbose
  loggers:
    redis: ${LOG_LEVEL_REDIS:WARN}
    tool_sync: ${LOG_LEVEL_TOOL_SYNC:INFO}
    tool_discovery: ${LOG_LEVEL_TOOL_DISCOVERY:INFO}
    mcp: ${LOG_LEVEL_MCP:WARN}

# OpenAI Configuration
openai:
  model: "gpt-4o-mini"
  temperature: 0
  max_tokens: 4000

# MCP Client Configuration
mcp:
  enabled: true
  servers:
    QuipMCPServer:
      transport: "streamable_http"
      reconnect_attempts: 5  # More retries in production
      reconnect_delay: 10    # Longer delay in production

# Agent Configuration
agent:
  prompts_dir: "src/agent/prompts"
  prompts:
    main_system: "main_system_prompt.txt"
    human_confirmation: "human_confirmation_prompt.txt"
    progress_report: "progress_report_prompt.txt"
  max_iterations: 10
  stream_mode:
    - "updates"
    - "messages" 
    - "custom"

# Redis Configuration - Production settings
redis:
  host: ${REDIS_HOST:redis-cluster.production.local}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:0}
  password: ${REDIS_PASSWORD}  # Required in production
  retry:
    max_attempts: ${REDIS_RETRY_MAX_ATTEMPTS:5}  # More retries in production
    base_delay: ${REDIS_RETRY_BASE_DELAY:2.0}    # Longer base delay
    max_delay: ${REDIS_RETRY_MAX_DELAY:60.0}     # Longer max delay

# Memory Configuration
memory:
  type: "in_memory"
  checkpoint_interval: 100

# Tool Synchronization Configuration - Production settings
tool_sync:
  enabled: true
  discovery_on_startup: true
  http_server:
    enabled: ${TOOL_SYNC_HTTP_ENABLED:true}
    host: ${TOOL_SYNC_HTTP_HOST:0.0.0.0}
    port: ${TOOL_SYNC_HTTP_PORT:5001}
    timeout: ${TOOL_SYNC_HTTP_TIMEOUT:10}  # Standard timeout for production
    discovery:
      timeout: ${TOOL_DISCOVERY_TIMEOUT:10}
      retry_attempts: ${TOOL_DISCOVERY_RETRY_ATTEMPTS:3}  # More retries for reliability
      retry_delay: ${TOOL_DISCOVERY_RETRY_DELAY:2}        # Longer delay for stability