# Agent Configuration
app:
  name: "agent"
  version: "1.0.0"
  description: "Agent Service for Quip Bot"

# Backend API Configuration
backend:
  url: "http://quip-backend-app:8080"  # Can be overridden by BACKEND_URL env var

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - console
    - file
  file_path: "logs/agent.log"

# OpenAI Configuration
openai:
  model: "gpt-4o-mini"
  temperature: 0
  max_tokens: 4000

# MCP Client Configuration (optional - can be empty for local tools only)
mcp:
  enabled: true  # Set to false to use local tools only
  servers:
    QuipMCPServer:
      # URL configured via environment variables for security
      # Use MCP_SERVER_URL_QUIPMCPSERVER or fallback to MCP_SERVER_URL
      transport: "streamable_http"
      reconnect_attempts: 3
      reconnect_delay: 5
    # Add more MCP servers here as needed
    # WeatherMCPServer:
    #   # URL configured via MCP_SERVER_URL_WEATHERMCPSERVER env var
    #   transport: "streamable_http"
    #   reconnect_attempts: 3
    #   reconnect_delay: 5

# Agent Configuration
agent:
  prompts_dir: "src/agent/prompts"
  prompts:
    main_system: "main_system_prompt.txt"
    human_confirmation: "human_confirmation_prompt.txt"
    progress_report: "progress_report_prompt.txt"
  max_iterations: 10
  stream_mode:
    - "updates"
    - "messages" 
    - "custom"

# Memory Configuration
memory:
  type: "in_memory"
  checkpoint_interval: 100